datasets:
- identifier: DK-Sor_sen2
  store: stac-store
  data_id: sentinel-2-l2a
  open_params:
    time_range:
    - '2020-01-01'
    - '2020-12-31'
    point:
    - 11.6446444
    - 55.4858694
    bbox_width: 4000
    spatial_res: 10
    asset_names:
    - B01
    - B02
    - B03
    - B04
    - B05
    - B06
    - B07
    - B08
    - B8A
    - B09
    - B11
    - B12
    - SCL
data_stores:
- identifier: storage
  store_id: file
  store_params:
    root: data_sentinel-2/DK-Sor
- identifier: esa-cci-store
  store_id: cciodp
- identifier: stac-store
  store_id: stac-cdse-ardc
  store_params:
    key: OX94JKCFEF1PLNVNAU2J
    secret: ceucxUr3s8yNhaP8k3g0FnQERKgm8SUfd9TdSFrF
- identifier: cds
  store_id: cds
  store_params:
    endpoint_url: https://cds.climate.copernicus.eu/api
    cds_api_key: d33a9d75-c4cc-406d-9f28-b94bf2ddd30f
    normalize_names: true
