datasets:
- identifier: IT-CA2_sen2
  store: stac-store
  data_id: sentinel-2-l2a
  open_params:
    time_range: &id001
    - '2020-01-01'
    - '2020-12-31'
    point:
    - 12.02603889
    - 42.37721944
    bbox_width: 4000
    spatial_res: 10
    asset_names:
    - B01
    - B02
    - B03
    - B04
    - B05
    - B06
    - B07
    - B08
    - B8A
    - B09
    - B11
    - B12
    - SCL
- identifier: IT-CA2_ccibiomass
  store: esa-cci-store
  grid_mapping: IT-CA2_sen2
  data_id: esacci.BIOMASS.yr.L4.AGB.multi-sensor.multi-platform.MERGED.6-0.100m
  open_params:
    time_range: *id001
data_stores:
- identifier: storage
  store_id: file
  store_params:
    root: data_sentinel-2_pc/IT-CA2
- identifier: esa-cci-store
  store_id: cciodp
- identifier: stac-store
  store_id: stac-pc-ardc
- identifier: cds
  store_id: cds
  store_params:
    endpoint_url: https://cds.climate.copernicus.eu/api
    cds_api_key: d33a9d75-c4cc-406d-9f28-b94bf2ddd30f
    normalize_names: true
